version: '3'

services:
  peru-data-processing:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env

  peru-cleandata-processing:
    build:
      context: .
      dockerfile: Dockerfile.cleanDB
    volumes:
      - .:/app
    env_file:
      - .env
